
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaprojeodevi.Yardim;

import Islemler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



public class yolculisteekrani extends javax.swing.JDialog implements ActionListener{
    DefaultTableModel model;
    Islemler islemler=new Islemler();
    
    /**
     * Creates new form yolculisteekrani
     */
    public yolculisteekrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel) yolcu_tablosu.getModel();
        YolcuGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        yolcu_tablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        soyadAlani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        yolcu_ekle = new javax.swing.JButton();
        adAlani = new javax.swing.JTextField();
        guzergahAlani = new javax.swing.JComboBox<>();
        plakaAlani = new javax.swing.JComboBox<>();
        gunAlani = new javax.swing.JComboBox<>();
        saatAlani = new javax.swing.JComboBox<>();
        koltukAlani = new javax.swing.JComboBox<>();
        kaptaninAdiAlani = new javax.swing.JComboBox<>();
        mesaj_yazisi = new javax.swing.JLabel();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        yolcu_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ad", "soyad", "guzergah", "plaka", "gun", "saat", "koltuk", "kaptanin_adi", "yolcu_numarasi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        yolcu_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yolcu_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(yolcu_tablosu);
        if (yolcu_tablosu.getColumnModel().getColumnCount() > 0) {
            yolcu_tablosu.getColumnModel().getColumn(0).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(1).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(2).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(3).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(4).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(5).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(6).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(7).setResizable(false);
            yolcu_tablosu.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad: ");

        jLabel3.setText("Guzergah: ");

        jLabel4.setText("Plaka: ");

        jLabel5.setText("Gun: ");

        jLabel6.setText("Saat: ");

        jLabel7.setText("Koltuk: ");

        jLabel9.setText("Kaptanin Adi: ");

        yolcu_ekle.setText("Yeni Yolcu Ekle");
        yolcu_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yolcu_ekleActionPerformed(evt);
            }
        });

        guzergahAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Istanbul-Sanliurfa", "Sanliurfa-Istanbul" }));
        guzergahAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzergahAlaniActionPerformed(evt);
            }
        });

        plakaAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "34-AB-483" }));

        gunAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01.01.2024", "02.01.2024", "03.01.2024", "04.01.2024","05.01.2024","06.01.2024","07.01.2024","08.01.2024","09.01.2024","10.01.2024" }));

        saatAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08.00", "09.00", "10.00", "11.00","12.00","13.00","14.00","15.00","16.00","17.00","18.00","19.00","20.00","21.00","22.00","23.00" }));

        koltukAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20"}));

        kaptaninAdiAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ali_Yilmaz", "Ahmet_Altin" }));

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        guncelle.setText("Yolcu Guncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setText("Yolcu Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56)
                                .addComponent(adAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(41, 41, 41))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(35, 35, 35)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plakaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guzergahAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gunAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(251, 251, 251)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saatAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(koltukAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kaptaninAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(yolcu_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(adAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saatAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(yolcu_ekle)
                    .addComponent(koltukAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guzergahAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(kaptaninAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plakaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gunAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(guncelle)
                        .addGap(26, 26, 26)
                        .addComponent(sil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    
    private void yolcu_ekleActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
       mesaj_yazisi.setText("");
       String ad=adAlani.getText();
       String soyad=soyadAlani.getText();
       String guzergah=guzergahAlani.getSelectedItem().toString();
       String plaka=plakaAlani.getSelectedItem().toString();    
       String gun=gunAlani.getSelectedItem().toString();
       String saat=saatAlani.getSelectedItem().toString();
       String koltuk=koltukAlani.getSelectedItem().toString();
       String kaptanin_adi=kaptaninAdiAlani.getSelectedItem().toString();
       islemler.yolcuEkle(ad,soyad,guzergah,plaka,gun,saat,koltuk,kaptanin_adi);
       mesaj_yazisi.setText("Yeni Yolcu Eklendi");
        YolcuGoruntule();
      
    }                                          
    public void YolcuGoruntule(){
        model.setRowCount(0);
        ArrayList<yolcubilgi>yolcular=new ArrayList<yolcubilgi>();
        yolcular=islemler.yolculariGetir();
        if(yolcular!=null){
            for(yolcubilgi yolcu:yolcular){
                Object[] eklenecek={yolcu.getAd(),yolcu.getSoyad(),yolcu.getGuzergah(),yolcu.getPlaka(),yolcu.getGun(),yolcu.getSaat(),yolcu.getKoltuk(),yolcu.getKaptanin_adi(),yolcu.getYolcu_numarasi()};
               model.addRow(eklenecek); 
            }}
        }
    private void guzergahAlaniActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void yolcu_tablosuMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        int selectedrow=yolcu_tablosu.getSelectedRow();
        adAlani.setText(model.getValueAt(selectedrow,0).toString()); 
        soyadAlani.setText(model.getValueAt(selectedrow,1).toString());
        guzergahAlani.setSelectedItem(model.getValueAt(selectedrow,2).toString());
        plakaAlani.setSelectedItem(model.getValueAt(selectedrow,3).toString());
        gunAlani.setSelectedItem(model.getValueAt(selectedrow,4).toString());
        saatAlani.setSelectedItem(model.getValueAt(selectedrow,5).toString());
        koltukAlani.setSelectedItem(model.getValueAt(selectedrow,6).toString());
        kaptaninAdiAlani.setSelectedItem(model.getValueAt(selectedrow,7).toString());
        
    }                                          

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String ad=adAlani.getText();
        String soyad=soyadAlani.getText();
        String guzergah=guzergahAlani.getSelectedItem().toString();
        String plaka=plakaAlani.getSelectedItem().toString();
        String gun=gunAlani.getSelectedItem().toString();
        String saat=saatAlani.getSelectedItem().toString();
        String koltuk=koltukAlani.getSelectedItem().toString();
        String kaptanin_adi=kaptaninAdiAlani.getSelectedItem().toString();
        
        
        int selectedrow=yolcu_tablosu.getSelectedRow();
        if(selectedrow==-1){
            if(model.getRowCount()==0){
                mesaj_yazisi.setText("yolcular tablosu su anda bos");
            }
            else{
                mesaj_yazisi.setText("Lutfen guncellenecek bir yolcu secin.");
            }
        }
        else{
            int yolcu_numarasi=(int)model.getValueAt(selectedrow,8);
            islemler.yolcuGuncelle(ad,soyad,guzergah,plaka,gun,saat,koltuk,kaptanin_adi,yolcu_numarasi);
            YolcuGoruntule();
            mesaj_yazisi.setText("yolcuBasariylaGuncellendi...");
        }
    }                                        

    private void silActionPerformed(java.awt.event.ActionEvent evt) {                                    
        mesaj_yazisi.setText("");
        int selectedrow=yolcu_tablosu.getSelectedRow();
        if(selectedrow==-1){
            if(model.getRowCount()==0){
                
            
             mesaj_yazisi.setText("yolcu tablosu su anda bos...");
            }
        else{
            mesaj_yazisi.setText("Lutfen silinecek bir yolcu secin...");    
        
     }}
        else{
                int yolcu_numarasi=(int)model.getValueAt(selectedrow,8);
                
                islemler.yolcuSil(yolcu_numarasi);
                YolcuGoruntule();
                mesaj_yazisi.setText("Yolcu basariyla silindi...");
                }
    }                                   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yolculisteekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yolculisteekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yolculisteekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yolculisteekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                yolculisteekrani dialog = new yolculisteekrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField adAlani;
    private javax.swing.JComboBox<String> gunAlani;
    private javax.swing.JButton guncelle;
    private javax.swing.JComboBox<String> guzergahAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kaptaninAdiAlani;
    private javax.swing.JComboBox<String> koltukAlani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JComboBox<String> plakaAlani;
    private javax.swing.JComboBox<String> saatAlani;
    private javax.swing.JButton sil;
    private javax.swing.JTextField soyadAlani;
    private javax.swing.JButton yolcu_ekle;
    private javax.swing.JTable yolcu_tablosu;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

